version: 2

project_name: zen

before:
  hooks:
    - go mod tidy

checksum:
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"

release:
  github:
    owner: Pavan-Silva
    name: go-zen
  draft: false
