# .goreleaser.yaml
# https://goreleaser.com

version: 2

project_name: zen

before:
  hooks:
    - go mod tidy

builds:
  - id: zenserver
    dir: ./cmd/zenserver
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: zen
    flags:
      - -trimpath

archives:
  - id: zenserver
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "README.md"
      - "LICENSE"
      - "examples/**/*"

checksum:
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"

release:
  github:
    owner: Pavan-Silva
    name: zen
  draft: false
