package zen

import (
	"fmt"
	"net/http"
	"sync"

	"github.com/Pavan-Silva/go-zen/internal/log"
	"github.com/Pavan-Silva/go-zen/scalar"
	"github.com/swaggo/swag"
)

// OpenAPIConfig configures how the API documentation is served. The spec
// content comes from swag; everything about the API itself (title, version,
// security definitions) is declared with annotations in your code.
type OpenAPIConfig struct {
	SpecPath         string         // Path to serve the generated spec JSON (default "/openapi.json").
	DocPath          string         // Path to serve the docs UI (default "/docs").
	DisableUI        bool           // When true, no documentation UI is served.
	SwagInstance     string         // Name of the registered swag instance (default swag.Name; matches "swag init --instanceName").
	SwaggerUIOptions map[string]any // Extra init options forwarded to Scalar.createApiReference (kept name for compatibility).
}

// OpenAPI serves a swaggo-generated OpenAPI specification and the embedded
// Scalar UI on a zen engine.
type OpenAPI struct {
	cfg OpenAPIConfig

	mu       sync.RWMutex
	specJSON []byte
}

// NewOpenAPI creates an OpenAPI adapter with the given configuration.
func NewOpenAPI(cfg OpenAPIConfig) *OpenAPI {
	if cfg.SpecPath == "" {
		cfg.SpecPath = "/openapi.json"
	}

	if cfg.DocPath == "" {
		cfg.DocPath = "/docs"
	}

	if cfg.SwagInstance == "" {
		cfg.SwagInstance = swag.Name
	}

	return &OpenAPI{cfg: cfg}
}

// SpecJSON returns the generated OpenAPI specification as JSON bytes. The
// document is produced once by the registered swag instance and cached; an
// error is returned when no swag documentation has been registered under the
// configured instance name.
func (o *OpenAPI) SpecJSON() ([]byte, error) {
	o.mu.RLock()
	cached := o.specJSON
	o.mu.RUnlock()
	if cached != nil {
		return cached, nil
	}

	o.mu.Lock()
	defer o.mu.Unlock()
	if o.specJSON != nil {
		return o.specJSON, nil
	}

	doc, err := swag.ReadDoc(o.cfg.SwagInstance)
	if err != nil {
		log.Error("openapi: %v - import your generated docs package (e.g. `_ \"myapp/docs\"`) or run `swag init`", err)
		return nil, fmt.Errorf("openapi: %w", err)
	}

	b := []byte(doc)
	o.specJSON = b
	return b, nil
}

// writeSpec serves the OpenAPI spec JSON on w.
func (o *OpenAPI) writeSpec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")

	data, err := o.SpecJSON()
	if err != nil {
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write(fmt.Appendf(nil, `{"error":%q}`+"\n", err.Error()))
		return
	}

	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(data)
}

// writeDoc serves the documentation UI HTML on w, or 404 when DisableUI is set.
func (o *OpenAPI) writeDoc(w http.ResponseWriter, _ *http.Request) {
	if o.cfg.DisableUI {
		w.WriteHeader(http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(scalar.UIHTML(o.cfg.SpecPath, o.cfg.SwaggerUIOptions)))
}

// SpecHandler returns an http.Handler that serves /openapi.json.
func (o *OpenAPI) SpecHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { o.writeSpec(w, r) })
}

// DocHandler returns an http.Handler that serves the API documentation UI.
// Returns a 404 handler when DisableUI is true.
func (o *OpenAPI) DocHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { o.writeDoc(w, r) })
}

// RouteRegistrar is the minimal interface a router must satisfy for
// RegisterRoutes. zen's Engine and RouterGroup implement it via HandleRaw.
type RouteRegistrar interface {
	HandleRaw(pattern string, handler http.Handler)
}

// RegisterRoutes registers the spec endpoint and optionally the docs UI on the
// given router. The docs UI is skipped when DisableUI is true.
func (o *OpenAPI) RegisterRoutes(r RouteRegistrar) {
	r.HandleRaw("GET "+o.cfg.SpecPath, http.HandlerFunc(o.writeSpec))

	if !o.cfg.DisableUI {
		r.HandleRaw("GET "+o.cfg.DocPath, http.HandlerFunc(o.writeDoc))
		r.HandleRaw("GET /openapi/ui/{path...}", http.StripPrefix("/openapi/ui/", http.FileServer(scalar.Assets())))
	}
}

// EnableAPIDocs serves swaggo-generated OpenAPI documentation on the engine:
// the spec JSON at /openapi.json and the embedded Scalar UI at /docs. The spec
// content comes from comment annotations on handlers and models — generate and
// import the docs package via `swag init`:
//
//	import _ "myapp/docs" // generated by "swag init"
//
//	r := zen.New(":8080")
//	r.EnableAPIDocs()
//
// Accepts an optional OpenAPIConfig and/or func(*OpenAPIConfig) options:
//
//	r.EnableAPIDocs(OpenAPIConfig{DisableUI: true})
//	r.EnableAPIDocs(func(c *OpenAPIConfig) { c.SpecPath = "/api/openapi.json" })
func (e *Engine) EnableAPIDocs(opts ...any) {
	cfg := OpenAPIConfig{}

	for _, opt := range opts {
		switch v := opt.(type) {
		case OpenAPIConfig:
			cfg = v
		case func(*OpenAPIConfig):
			v(&cfg)
		default:
			panic(fmt.Sprintf("zen: EnableAPIDocs expects OpenAPIConfig or func(*OpenAPIConfig), got %T", opt))
		}
	}

	NewOpenAPI(cfg).RegisterRoutes(e)
}
