package auth

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"strings"

	"golang.org/x/crypto/bcrypt"
	"golang.org/x/crypto/pbkdf2"
)

// ValidatePassword securely validates a plaintext password against a stored hash.
// It hashes the plain password using the same algorithm as storedHash and compares
// using constant-time comparison to prevent timing attacks.
// The storedHash should be in the format: algorithm$salt$hash (e.g., "sha256$salt$hash").
func ValidatePassword(storedHash, plain string) bool {
	if storedHash == "" || plain == "" {
		return false
	}

	// Support standard bcrypt hashes directly.
	if strings.HasPrefix(storedHash, "$2a$") || strings.HasPrefix(storedHash, "$2b$") || strings.HasPrefix(storedHash, "$2y$") {
		return bcrypt.CompareHashAndPassword([]byte(storedHash), []byte(plain)) == nil
	}

	before, after, ok := strings.Cut(storedHash, "$")
	if !ok {
		return false
	}

	algorithm := before
	rest := after
	parts := strings.SplitN(rest, "$", 2)
	if len(parts) != 2 {
		return false
	}

	salt := parts[0]
	existingHash := parts[1]

	newHash, err := HashPassword(algorithm, plain, salt)
	if err != nil {
		return false
	}

	// Keep compatibility with legacy sha256 hashes generated by earlier versions.
	if algorithm == "sha256" {
		legacyHash, legacyErr := hashPasswordLegacySHA256(plain, salt)
		if legacyErr == nil && subtle.ConstantTimeCompare([]byte(existingHash), []byte(legacyHash)) == 1 {
			return true
		}
	}

	if algorithm == "bcrypt" {
		return bcrypt.CompareHashAndPassword([]byte(existingHash), []byte(plain)) == nil
	}

	return subtle.ConstantTimeCompare([]byte(existingHash), []byte(newHash)) == 1
}

// HashPassword hashes a password using the specified algorithm.
// Supported algorithms: "sha256", "bcrypt".
// For bcrypt, salt is optional as bcrypt generates its own internally.
func HashPassword(algorithm, password, salt string) (string, error) {
	switch algorithm {
	case "sha256":
		if salt == "" {
			return "", fmt.Errorf("salt is required for sha256")
		}
		hash := pbkdf2.Key([]byte(password), []byte(salt), 10000, 32, sha256.New)
		return base64.RawURLEncoding.EncodeToString(hash), nil
	case "bcrypt":
		hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
		return string(hash), err
	default:
		return "", fmt.Errorf("unsupported hashing algorithm: %s", algorithm)
	}
}

// hashPasswordLegacySHA256 reproduces pre-vNext sha256 password hashing for compatibility.
func hashPasswordLegacySHA256(password, salt string) (string, error) {
	if salt == "" {
		return "", fmt.Errorf("salt is required for sha256")
	}
	data := []byte(password + salt)
	hash := make([]byte, 32)
	copy(hash, data)
	for range 10000 {
		h := sha256.Sum256(hash)
		copy(hash, h[:])
	}
	return base64.RawURLEncoding.EncodeToString(hash), nil
}
