// Package openapi serves swaggo-generated OpenAPI documentation through zen's
// embedded Scalar UI.
//
// The specification itself is produced by swag (github.com/swaggo/swag) from
// comment annotations on handlers and models. Run "swag init", import the
// generated docs package so it registers itself, and point zen at it:
//
//	import _ "myapp/docs" // generated by "swag init"
//
//	doc := openapi.New(openapi.Config{})
//	doc.RegisterRoutes(r)
package openapi

import (
	"fmt"
	"net/http"
	"sync"

	"github.com/Pavan-Silva/go-zen"
	"github.com/Pavan-Silva/go-zen/internal/log"
	"github.com/swaggo/swag"
)

// Config configures how the documentation is served. The spec content comes
// from swag; everything about the API itself (title, version, security
// definitions) is declared with annotations in your code.
type Config struct {
	SpecPath         string         // Path to serve the generated spec JSON (default "/openapi.json").
	DocPath          string         // Path to serve the docs UI (default "/docs").
	DisableUI        bool           // When true, no documentation UI is served.
	SwagInstance     string         // Name of the registered swag instance (default swag.Name; matches "swag init --instanceName").
	SwaggerUIOptions map[string]any // Extra init options forwarded to Scalar.createApiReference (kept name for compatibility).
}

// OpenAPI serves a swaggo-generated OpenAPI specification and the embedded
// Scalar UI on a zen engine.
type OpenAPI struct {
	cfg Config

	mu       sync.RWMutex
	specJSON []byte
}

// New creates an OpenAPI adapter with the given configuration.
func New(cfg Config) *OpenAPI {
	if cfg.SpecPath == "" {
		cfg.SpecPath = "/openapi.json"
	}

	if cfg.DocPath == "" {
		cfg.DocPath = "/docs"
	}

	if cfg.SwagInstance == "" {
		cfg.SwagInstance = swag.Name
	}

	return &OpenAPI{cfg: cfg}
}

// SpecJSON returns the generated OpenAPI specification as JSON bytes. The
// document is produced once by the registered swag instance and cached; an
// error is returned when no swag documentation has been registered under the
// configured instance name.
func (o *OpenAPI) SpecJSON() ([]byte, error) {
	o.mu.RLock()
	cached := o.specJSON
	o.mu.RUnlock()
	if cached != nil {
		return cached, nil
	}

	o.mu.Lock()
	defer o.mu.Unlock()
	if o.specJSON != nil {
		return o.specJSON, nil
	}

	doc, err := swag.ReadDoc(o.cfg.SwagInstance)
	if err != nil {
		log.Error("openapi: %v - import your generated docs package (e.g. `_ \"myapp/docs\"`) or run `swag init`", err)
		return nil, fmt.Errorf("openapi: %w", err)
	}

	b := []byte(doc)
	o.specJSON = b
	return b, nil
}

// writeSpec serves the OpenAPI spec JSON on w.
func (o *OpenAPI) writeSpec(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")

	data, err := o.SpecJSON()
	if err != nil {
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write(fmt.Appendf(nil, `{"error":%q}`+"\n", err.Error()))
		return
	}

	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(data)
}

// writeDoc serves the documentation UI HTML on w, or 404 when DisableUI is set.
func (o *OpenAPI) writeDoc(w http.ResponseWriter, _ *http.Request) {
	if o.cfg.DisableUI {
		w.WriteHeader(http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(uiHTML(o)))
}

// SpecHandler returns a HandlerFunc that serves /openapi.json.
func (o *OpenAPI) SpecHandler() zen.HandlerFunc {
	return func(c *zen.Ctx) { o.writeSpec(c.Response, c.Request) }
}

// DocHandler returns a HandlerFunc that serves the API documentation UI.
// Returns a 404 handler when DisableUI is true.
func (o *OpenAPI) DocHandler() zen.HandlerFunc {
	return func(c *zen.Ctx) { o.writeDoc(c.Response, c.Request) }
}

// RegisterRoutes registers the spec endpoint and optionally the docs UI on the engine.
// The docs UI is skipped when DisableUI is true.
func (o *OpenAPI) RegisterRoutes(r *zen.Engine) {
	r.HandleRaw("GET "+o.cfg.SpecPath, http.HandlerFunc(o.writeSpec))

	if !o.cfg.DisableUI {
		r.HandleRaw("GET "+o.cfg.DocPath, http.HandlerFunc(o.writeDoc))

		if uiAssets != nil {
			r.HandleRaw("GET /openapi/ui/{path...}", http.StripPrefix("/openapi/ui/", http.FileServer(uiAssets)))
		}
	}
}
